-- TMSL AI — College Knowledge Engine
-- Snowflake Schema Setup
-- Run this script in your Snowflake worksheet to set up the database

-- Create database and schema
CREATE DATABASE IF NOT EXISTS TMSL_AI;
USE DATABASE TMSL_AI;
CREATE SCHEMA IF NOT EXISTS PUBLIC;
USE SCHEMA PUBLIC;

-- Create warehouse
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH
  WITH WAREHOUSE_SIZE = 'X-SMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

USE WAREHOUSE COMPUTE_WH;

-- Documents table
CREATE TABLE IF NOT EXISTS DOCUMENTS (
  DOCUMENT_ID VARCHAR(36) PRIMARY KEY,
  TITLE VARCHAR(500) NOT NULL,
  FILENAME VARCHAR(500) NOT NULL,
  CATEGORY VARCHAR(50) DEFAULT 'general',
  DEPARTMENT VARCHAR(200) DEFAULT '',
  SOURCE VARCHAR(500) DEFAULT '',
  FULL_TEXT TEXT,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Document chunks with vector embeddings
CREATE TABLE IF NOT EXISTS DOCUMENT_CHUNKS (
  CHUNK_ID VARCHAR(36) PRIMARY KEY,
  DOCUMENT_ID VARCHAR(36) NOT NULL REFERENCES DOCUMENTS(DOCUMENT_ID),
  CHUNK_INDEX INTEGER NOT NULL,
  CONTENT TEXT NOT NULL,
  EMBEDDING VECTOR(FLOAT, 1024),
  METADATA VARIANT,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Queries/chat history
CREATE TABLE IF NOT EXISTS QUERIES (
  QUERY_ID VARCHAR(36) PRIMARY KEY,
  QUESTION TEXT NOT NULL,
  ANSWER TEXT,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Query-to-source mappings
CREATE TABLE IF NOT EXISTS QUERY_SOURCES (
  QUERY_ID VARCHAR(36) NOT NULL REFERENCES QUERIES(QUERY_ID),
  CHUNK_ID VARCHAR(36) NOT NULL REFERENCES DOCUMENT_CHUNKS(CHUNK_ID),
  RELEVANCE_SCORE FLOAT,
  PRIMARY KEY (QUERY_ID, CHUNK_ID)
);

-- Events extracted from documents
CREATE TABLE IF NOT EXISTS EVENTS (
  EVENT_ID VARCHAR(36) PRIMARY KEY,
  DOCUMENT_ID VARCHAR(36) REFERENCES DOCUMENTS(DOCUMENT_ID),
  TITLE VARCHAR(500) NOT NULL,
  DESCRIPTION TEXT,
  EVENT_DATE DATE,
  REGISTRATION_DEADLINE DATE,
  LOCATION VARCHAR(500),
  ORGANIZER VARCHAR(500),
  ELIGIBILITY TEXT,
  CATEGORY VARCHAR(50) DEFAULT 'event'
);

-- Performance Optimization Note
-- Note: Snowflake uses automatic micro-partitioning instead of traditional B-Tree indexes. 
-- For massive scale, clustering keys can be applied:
-- ALTER TABLE DOCUMENT_CHUNKS CLUSTER BY (DOCUMENT_ID);
-- ALTER TABLE EVENTS CLUSTER BY (EVENT_DATE);
-- ALTER TABLE QUERIES CLUSTER BY (TO_DATE(CREATED_AT));
