-- TMSL AI — College Knowledge Engine
-- Snowflake Schema Setup
-- Optimized for Snowflake Standard, Trial, and Enterprise editions

CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH
  WITH WAREHOUSE_SIZE = 'X-SMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

CREATE DATABASE IF NOT EXISTS TMSL_AI;
USE DATABASE TMSL_AI;
CREATE SCHEMA IF NOT EXISTS PUBLIC;
USE SCHEMA PUBLIC;
USE WAREHOUSE COMPUTE_WH;

-- 1. Document Registry Table
CREATE TABLE IF NOT EXISTS DOCUMENTS (
    DOCUMENT_ID VARCHAR(36) PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    CATEGORY VARCHAR(64) NOT NULL,
    RAW_CONTENT TEXT NOT NULL,
    CHUNK_COUNT INT DEFAULT 0,
    UPLOADED_BY VARCHAR(64) DEFAULT 'Admin',
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 2. Document Chunks Table (Compatible with all Snowflake tiers)
CREATE TABLE IF NOT EXISTS DOCUMENT_CHUNKS (
    CHUNK_ID VARCHAR(36) PRIMARY KEY,
    DOCUMENT_ID VARCHAR(36) REFERENCES DOCUMENTS(DOCUMENT_ID) ON DELETE CASCADE,
    DOCUMENT_TITLE VARCHAR(255) NOT NULL,
    CATEGORY VARCHAR(64) NOT NULL,
    CHUNK_INDEX INT NOT NULL,
    CHUNK_TEXT TEXT NOT NULL,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 3. Events Intelligence Table
CREATE TABLE IF NOT EXISTS EVENTS (
    EVENT_ID VARCHAR(36) PRIMARY KEY,
    DOCUMENT_ID VARCHAR(36) REFERENCES DOCUMENTS(DOCUMENT_ID) ON DELETE CASCADE,
    EVENT_NAME VARCHAR(255) NOT NULL,
    EVENT_TYPE VARCHAR(64) NOT NULL,
    START_DATE TIMESTAMP_NTZ,
    LOCATION VARCHAR(255),
    ORGANIZER VARCHAR(255),
    REGISTRATION_DEADLINE TIMESTAMP_NTZ,
    ELIGIBILITY TEXT,
    DETAILS TEXT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 4. Audit & Analytics Queries Table
CREATE TABLE IF NOT EXISTS QUERIES (
    QUERY_ID VARCHAR(36) PRIMARY KEY,
    USER_QUERY TEXT NOT NULL,
    AI_RESPONSE TEXT NOT NULL,
    CITATIONS VARIANT,
    LATENCY_MS INT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
